version: "3.1"

services:
  redmine:
    image: redmine:4.2.3
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./.docker/redmine/files:/usr/src/redmine/files
      - ./.docker/redmine/sqlite:/usr/src/redmine/sqlite
